name: compGatesTest1

 
on:
  push: 
    branches: [ "main" ]

jobs:
  merge:
    runs-on: self-hosted
    steps:
      - name: Dummy job
        run: |
          echo "Building on main branch!"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
